name: CD-Build And Deploy

# 작업진행은 main, develop브랜치에서만 작동이 되도록
on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-22.04 #latest라고 적어도됨.
    steps:
      # 소스코드 Checkout
      - name: Code Checkout
        uses: actions/checkout@main

      # Node Install, 현재 로컬과 동기화
      - name: Set Up Node
        uses: actions/setup-node@main
        with:
          node-version: 19.7

      - name: Npm Install
        run: npm install

      - name: confirm
        run: ls ./ |
          echo "in src"|
          ls ./src

      - name: Npm Build
        run: npm run build

      # 배포, github_token은 별도로 필요 항목은 아니다.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $
          publish_branch: gh-pages
          publish_dir: ./build
